import { DeploymentRequest } from './types'

export const ACME_MOTORS_REQUEST: DeploymentRequest = {
  client: 'Acme Motors',
  factory_type: 'automotive_assembly',
  location: 'Detroit, MI — Plant 4',
  amr_count: 8,
  payload_range_kg: [60, 100],
  primary_task: 'Inter-zone material transport between assembly stations',
  special_requirements: [
    'Must interface with Manhattan Associates WMS v3.2',
    'Heavy parts on pallets — center of gravity varies by load type',
    'Zone B has 4.5% ramp gradient to mezzanine level',
    '24/7 three-shift continuous operation',
    'Precision docking at assembly line stations (±5mm)',
  ],
}

export const FACTORY_SPEC = {
  client: 'Acme Motors',
  factory_type: 'automotive_assembly',
  location: 'Detroit, MI — Plant 4',
  zones: [
    { id: 'A', name: 'Raw Materials Intake', area_sqm: 3000 },
    { id: 'B', name: 'Sub-Assembly', area_sqm: 4000 },
    { id: 'C', name: 'Final Assembly', area_sqm: 3500 },
    { id: 'D', name: 'Finished Goods & QC', area_sqm: 1500 },
  ],
  aisles: [
    { id: 'A1', width_m: 3.2, length_m: 45, connects: ['A', 'B'], surface: 'epoxy_coated' },
    { id: 'A2', width_m: 2.8, length_m: 30, connects: ['B', 'C'], surface: 'sealed_concrete' },
    { id: 'A3', width_m: 3.5, length_m: 25, connects: ['C', 'D'], surface: 'epoxy_coated' },
  ],
  ramps: [
    { id: 'R1', from: 'B', to: 'mezzanine_B', gradient_pct: 4.5, length_m: 8 },
  ],
  doors: [
    { id: 'D1', width_m: 2.8, type: 'automatic_roller', location: 'Zone A entrance' },
    { id: 'D2', width_m: 3.0, type: 'automatic_roller', location: 'Zone D shipping dock' },
  ],
  charger_locations: [
    { id: 'CL1', zone: 'A', position: 'NW corner', electrical_kw: 7.2 },
    { id: 'CL2', zone: 'C', position: 'SE corner', electrical_kw: 7.2 },
  ],
  wifi: {
    coverage_pct: 95,
    dead_zones: ['Zone C northeast corner — structural interference from steel support column'],
    ap_count: 12,
    protocol: '802.11ax (Wi-Fi 6)',
  },
  wms: {
    system: 'Manhattan Associates',
    version: '3.2',
    api_type: 'REST',
    events: ['task_dispatch', 'location_update', 'priority_change', 'task_complete'],
  },
  environment: {
    temperature_range_c: [15, 35],
    humidity_pct: [30, 60],
    floor_surface: 'sealed_concrete_and_epoxy',
    ceiling_height_m: 8.5,
    pedestrian_zones: ['Zone A main aisle (shift change)', 'Break room corridor between B and C'],
  },
  operational: {
    shifts: 3,
    hours: '24/7',
    peak_traffic: ['06:00-07:00 shift change', '14:00-15:00 shift change', '22:00-23:00 shift change'],
    daily_transport_tasks: 380,
  },
}

export const ROBOT_CATALOG = [
  {
    model: 'HeavyLift-X200',
    manufacturer: 'Orizon Robotics',
    payload_kg: 120,
    speed_range_ms: [0.5, 1.5],
    dimensions_mm: { l: 800, w: 600, h: 350 },
    battery: { type: 'LiFePO4', voltage: 48, capacity_ah: 30, runtime_h: 8 },
    charging: { type: 'contact_based', time_full_h: 2 },
    max_ramp_pct: 5,
    navigation: ['LiDAR SLAM', 'visual odometry', 'UWB beacon'],
    floor_types: ['sealed_concrete', 'epoxy', 'tile'],
    wms_protocols: ['REST', 'MQTT', 'OPC-UA'],
    ip_rating: 'IP54',
    best_for: 'Heavy material transport in automotive and manufacturing',
    price_range: '$45,000-55,000',
  },
  {
    model: 'LightRunner-S100',
    manufacturer: 'Orizon Robotics',
    payload_kg: 30,
    speed_range_ms: [1.0, 3.0],
    dimensions_mm: { l: 500, w: 400, h: 250 },
    battery: { type: 'Li-ion', voltage: 24, capacity_ah: 20, runtime_h: 12 },
    charging: { type: 'contact_based', time_full_h: 1.5 },
    max_ramp_pct: 8,
    navigation: ['LiDAR SLAM', 'visual odometry'],
    floor_types: ['sealed_concrete', 'epoxy', 'tile', 'anti-static', 'cleanroom_grade'],
    wms_protocols: ['REST', 'MQTT'],
    ip_rating: 'IP42',
    best_for: 'Fast small-part delivery in semiconductor, labs, clean rooms',
    price_range: '$28,000-35,000',
  },
  {
    model: 'ConveyorLink-C150',
    manufacturer: 'Orizon Robotics',
    payload_kg: 50,
    speed_range_ms: [0.8, 2.0],
    dimensions_mm: { l: 700, w: 550, h: 400 },
    battery: { type: 'LiFePO4', voltage: 48, capacity_ah: 25, runtime_h: 10 },
    charging: { type: 'wireless_inductive', time_full_h: 1.5 },
    max_ramp_pct: 6,
    navigation: ['LiDAR SLAM', 'conveyor_docking_sensor'],
    floor_types: ['sealed_concrete', 'epoxy', 'food_grade'],
    wms_protocols: ['REST', 'MQTT', 'Modbus TCP'],
    ip_rating: 'IP65',
    conveyor_interface: 'belt-to-belt automatic transfer',
    best_for: 'Food production, packaging lines, continuous flow operations',
    price_range: '$38,000-48,000',
  },
  {
    model: 'PrecisionDock-P80',
    manufacturer: 'Orizon Robotics',
    payload_kg: 80,
    speed_range_ms: [0.3, 1.2],
    dimensions_mm: { l: 750, w: 580, h: 320 },
    battery: { type: 'LiFePO4', voltage: 48, capacity_ah: 35, runtime_h: 10 },
    charging: { type: 'contact_based', time_full_h: 2.5 },
    max_ramp_pct: 4,
    navigation: ['LiDAR SLAM', 'visual odometry', 'precision_docking_camera'],
    floor_types: ['sealed_concrete', 'epoxy'],
    wms_protocols: ['REST', 'MQTT', 'OPC-UA'],
    ip_rating: 'IP54',
    docking_precision_mm: 2,
    best_for: 'Precision assembly line docking, semiconductor wafer transport',
    price_range: '$52,000-62,000',
  },
]

export const FLEET_STATUS_ACME = {
  client: 'Acme Motors',
  timestamp: '2026-06-18T10:30:00Z',
  fleet: [
    { robot_id: 'AMR-001', model: 'HeavyLift-X200', status: 'active', battery_pct: 72, current_task: 'transport_zone_a_to_b', position: { x: 15.2, y: 30.1 }, speed_ms: 1.1 },
    { robot_id: 'AMR-002', model: 'HeavyLift-X200', status: 'active', battery_pct: 58, current_task: 'transport_zone_b_to_c', position: { x: 45.0, y: 12.3 }, speed_ms: 0.9 },
    { robot_id: 'AMR-003', model: 'HeavyLift-X200', status: 'en_route_to_charger', battery_pct: 28, current_task: 'charging', position: { x: 8.1, y: 5.2 }, speed_ms: 0.5 },
    { robot_id: 'AMR-004', model: 'HeavyLift-X200', status: 'active', battery_pct: 85, current_task: 'transport_zone_c_to_d', position: { x: 62.3, y: 18.7 }, speed_ms: 1.2 },
    { robot_id: 'AMR-005', model: 'HeavyLift-X200', status: 'active', battery_pct: 64, current_task: 'transport_zone_a_to_b', position: { x: 22.1, y: 35.4 }, speed_ms: 1.0 },
    { robot_id: 'AMR-006', model: 'HeavyLift-X200', status: 'charging', battery_pct: 45, current_task: 'charging_at_cd1', position: { x: 5.0, y: 5.0 }, speed_ms: 0 },
    { robot_id: 'AMR-007', model: 'HeavyLift-X200', status: 'active', battery_pct: 35, current_task: 'transport_zone_c_to_d', position: { x: 70.2, y: 22.8 }, speed_ms: 0.8 },
    { robot_id: 'AMR-008', model: 'HeavyLift-X200', status: 'active', battery_pct: 91, current_task: 'standby_zone_b', position: { x: 38.5, y: 20.0 }, speed_ms: 0 },
  ],
  alerts: [
    { type: 'low_battery', robot_id: 'AMR-003', severity: 'info', message: 'En route to charger CD-1, ETA 2min' },
    { type: 'low_battery', robot_id: 'AMR-007', severity: 'warning', message: 'Battery at 35%, will need charging within 45min' },
    { type: 'maintenance_due', robot_id: 'AMR-005', severity: 'warning', message: 'LiDAR calibration due in 48h (1,200 operating hours reached)' },
  ],
  stats: {
    tasks_completed_today: 312,
    average_task_time_min: 4.2,
    fleet_uptime_pct: 91,
    total_distance_km_today: 45.8,
    throughput_tasks_per_hour: 42,
  },
}
